[project]
name = "ppo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "gymnasium[accept-rom-license,atari]>=1.2.0",
    "opencv-python>=4.12.0.88",
    "pygame>=2.6.1",
    "stable-baselines3>=2.7.0",
]
